name: tests

on:
  push:
      branches: [main, beta]

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: testing

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: sail
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testing
        ports:
          - 5434:5432
        options: >-
          --health-cmd "pg_isready -U sail -d testing"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: testing
      DB_USERNAME: sail
      DB_PASSWORD: password

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: ffi
          coverage: xdebug
          ini-values: ffi.enable=true

      - name: setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: install node dependencies
        run: npm i

      - name: install dependencies
        run: |
          composer install --no-interaction --prefer-dist --no-plugins --no-scripts
          composer dump-autoload --no-scripts
          composer install --no-interaction --prefer-dist

      - name: copy env file
        run: cp .env.example .env

      - name: generate application key
        run: php artisan key:generate

      - name: build assets
        run: npm run build

      - name: run type tests
        run: composer type

      - name: run coverage tests
        run: composer coverage
